// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-WjXv1t7DsKFZBudBhJrPtHSBZeJmS6M',
    appId: '1:1005013508838:web:83aa5549e31ac2afd61127',
    messagingSenderId: '1005013508838',
    projectId: 'yalla-7agz-dc31c',
    authDomain: 'yalla-7agz-dc31c.firebaseapp.com',
    storageBucket: 'yalla-7agz-dc31c.firebasestorage.app',
    measurementId: 'G-XEEMKMKSMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9P7lP2FuKgsMsNmCGYcg_wU7rnOe1q5U',
    appId: '1:1005013508838:android:1e57b961ef4d3ab8d61127',
    messagingSenderId: '1005013508838',
    projectId: 'yalla-7agz-dc31c',
    storageBucket: 'yalla-7agz-dc31c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYMChtelc9paD8khywH9ciTdA9PF7_PTI',
    appId: '1:1005013508838:ios:25d9ca0dc81e9459d61127',
    messagingSenderId: '1005013508838',
    projectId: 'yalla-7agz-dc31c',
    storageBucket: 'yalla-7agz-dc31c.firebasestorage.app',
    iosClientId: '1005013508838-mc8jiedpfj9jnq4vk7knr2alkui4iqn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.malab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYMChtelc9paD8khywH9ciTdA9PF7_PTI',
    appId: '1:1005013508838:ios:25d9ca0dc81e9459d61127',
    messagingSenderId: '1005013508838',
    projectId: 'yalla-7agz-dc31c',
    storageBucket: 'yalla-7agz-dc31c.firebasestorage.app',
    iosClientId: '1005013508838-mc8jiedpfj9jnq4vk7knr2alkui4iqn3.apps.googleusercontent.com',
    iosBundleId: 'com.example.malab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-WjXv1t7DsKFZBudBhJrPtHSBZeJmS6M',
    appId: '1:1005013508838:web:6678112ec971b538d61127',
    messagingSenderId: '1005013508838',
    projectId: 'yalla-7agz-dc31c',
    authDomain: 'yalla-7agz-dc31c.firebaseapp.com',
    storageBucket: 'yalla-7agz-dc31c.firebasestorage.app',
    measurementId: 'G-KRR6HQGJSK',
  );
}
